package giuseppetavella.demo_login_system.services;

import giuseppetavella.demo_login_system.entities.Company;
import giuseppetavella.demo_login_system.entities.User;
import giuseppetavella.demo_login_system.entities.checklists.Checklist;
import giuseppetavella.demo_login_system.entities.clients.ClientAddress;
import giuseppetavella.demo_login_system.entities.shifts.Shift;
import giuseppetavella.demo_login_system.entities.shifts.ShiftDay;
import giuseppetavella.demo_login_system.helpers.AuthorizationHelper;
import giuseppetavella.demo_login_system.payloads.in_request.NewShiftSentDTO;
import giuseppetavella.demo_login_system.payloads.in_response.*;
import giuseppetavella.demo_login_system.repositories.ShiftDaysRepository;
import giuseppetavella.demo_login_system.repositories.ShiftsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.DayOfWeek;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Service
public class ShiftsService {

    @Autowired
    private ShiftsRepository shiftsRepository;
    
    @Autowired
    private ShiftDaysRepository shiftDaysRepository;
    
    @Autowired
    private ClientAddressesService clientAddressesService;
    
    @Autowired
    private ChecklistsService checklistsService;
    
    @Autowired
    private ChecklistEntriesService checklistEntriesService;

    private static final Map<DayOfWeek, String> DAY_ABBR_IT = Map.of(
            DayOfWeek.MONDAY,    "LUN",
            DayOfWeek.TUESDAY,   "MAR",
            DayOfWeek.WEDNESDAY, "MER",
            DayOfWeek.THURSDAY,  "GIO",
            DayOfWeek.FRIDAY,    "VEN",
            DayOfWeek.SATURDAY,  "SAB",
            DayOfWeek.SUNDAY,    "DOM"
    );

    private static final List<DayOfWeek> DAY_ORDER = List.of(
            DayOfWeek.MONDAY, DayOfWeek.TUESDAY, DayOfWeek.WEDNESDAY,
            DayOfWeek.THURSDAY, DayOfWeek.FRIDAY, DayOfWeek.SATURDAY, DayOfWeek.SUNDAY
    );

    

    /**
     * Shift -> Shift DTO
     * 
     * @return
     */
    public ShiftToSendDTO toShiftDTO(Shift shift) 
    {

        Checklist checklist = shift.getChecklist();
        ClientAddress clientAddress = shift.getClientAddress();
        
        List<ChecklistEntryToSendDTO> entriesDTO = this.checklistEntriesService.getEntriesByChecklistAsDTO(checklist);

        List<ShiftDayToSendDTO> shiftDaysToSendDTO = this.findShiftDaysByShiftDTO(shift);
        
        ClientAddressToSendDTO clientAddressToSendDTO = new ClientAddressToSendDTO(clientAddress);

        ChecklistToSendDTO checklistToSendDTO = new ChecklistToSendDTO(checklist, entriesDTO);

        /**
         * A pre-defined shift name.
         * in a format like "client - checklist - days - time"
         * (not generated by user)
         *
         */
        String clientName = shift.getClientAddress().getClient().getLegalName();
        String clientAddressName = shift.getClientAddress().getAddressName();
        String timeRange = shift.getStartTime() + "-" + shift.getEndTime();
        List<DayOfWeek> daysOfWeek = shiftDaysToSendDTO.stream().map(shiftDay -> shiftDay.getDay()).toList();
        String daysStr = this.formatDays(daysOfWeek);
        
        String shiftName = clientName + " - " + clientAddressName + " - " + daysStr + " - " + timeRange;
        
        return new ShiftToSendDTO(
                shift,
                shiftDaysToSendDTO,
                clientAddressToSendDTO,
                checklistToSendDTO,
                shiftName
        );
        
    }


    /**
     * Find the shift days of the shift.
     * 
     * @param shift
     * @return
     */
    public List<ShiftDay> findShiftDaysByShift(Shift shift)
    {
        return this.shiftDaysRepository.findByShift(shift);
    }
    
    public List<ShiftDayToSendDTO> findShiftDaysByShiftDTO(Shift shift)
    {
        return this.findShiftDaysByShift(shift)
                    .stream()
                    .map(ShiftDayToSendDTO::new)
                    .toList();
    }
    
    
    /**
     * Add a shift.
     * 
     * @param company
     * @param body
     * @return
     */
    @Transactional
    public ShiftToSendDTO addShift(Company company, NewShiftSentDTO body) 
    {
        
        ClientAddress clientAddressFromDB = this.clientAddressesService.findById(body.clientAddressId());
        
        Checklist checklistFromDB = this.checklistsService.findById(body.checklistId());
        
        // check that client address and checklist belong to the same company 
        // that is trying to add the shift
        AuthorizationHelper.requireSameCompany(company, clientAddressFromDB.getClient().getCompany());
        
        AuthorizationHelper.requireSameCompany(company, checklistFromDB.getCompany());
        
       
        Shift newShift = new Shift(
                clientAddressFromDB,
                checklistFromDB,
                body.startDate(),
                body.endDate(),
                body.startTime(),
                body.endTime()
        );
        
        // save the shift in DB
        Shift shiftFromDB = this.shiftsRepository.save(newShift);
        
        // save the days of the shift in DB
        
        // but first, map the days to a ShiftDay non-managed instance
        List<ShiftDay> shiftDays = body.days()
                                    .stream()
                                    .map(day -> new ShiftDay(shiftFromDB, day))
                                    .toList();
        
        // save shift days
        this.shiftDaysRepository.saveAll(shiftDays);
        
        return this.toShiftDTO(shiftFromDB);
        
    }
    
    
    /**
     * Find all shifts between two dates.
     */
    public List<Shift> findShiftsBetween(Company company, LocalDate from, LocalDate to) {
        if (from == null && to == null) return shiftsRepository.findShifts(company);
        if (from == null) return shiftsRepository.findShiftsUntil(company, to);
        if (to == null)   return shiftsRepository.findShiftsFrom(company, from);
        return shiftsRepository.findShiftsBetween(company, from, to);
    }

    public List<ShiftToSendDTO> findShiftsBetweenDTO(Company company, 
                                                     LocalDate startDate, 
                                                     LocalDate endDate) 
    {
        return this
                .findShiftsBetween(company, startDate, endDate)
                .stream()
                .map(this::toShiftDTO)
                .toList();   
    }
    
    

    /**
     * Find all shifts of an operator.
     */
    // public List<Shift> findShiftsByOperator(User operator) {
    //     return shiftsRepository.findShiftsByOperator(operator);
    // }
    //
    // /**
    //  * Find all shifts of an operator between two dates.
    //  */
    // public List<Shift> findShiftsByOperatorBetween(User operator, LocalDate startDate, LocalDate endDate) {
    //     return shiftsRepository.findShiftsByOperatorBetween(operator, startDate, endDate);
    // }
    //
    // /**
    //  * Find all operators that have shifts between two dates.
    //  */
    // public List<User> findOperatorsBetween(LocalDate startDate, LocalDate endDate) {
    //     return shiftsRepository.findOperatorsBetween(startDate, endDate);
    // }
    //
    // /**
    //  * Find all operators that have no shifts between two dates.
    //  */
    // public List<User> findOperatorsWithoutShiftsBetween(LocalDate startDate, LocalDate endDate) {
    //     return shiftsRepository.findOperatorsWithoutShiftsBetween(startDate, endDate);
    // }



    private String formatDays(List<DayOfWeek> days) {

        // sort by week order
        List<DayOfWeek> sorted = days.stream()
                .sorted(Comparator.comparingInt(DAY_ORDER::indexOf))
                .toList();

        List<String> groups = new ArrayList<>();
        int i = 0;

        while (i < sorted.size()) {
            int start = i;

            // find end of consecutive sequence
            while (i + 1 < sorted.size() &&
                    DAY_ORDER.indexOf(sorted.get(i + 1)) == DAY_ORDER.indexOf(sorted.get(i)) + 1) {
                i++;
            }

            if (start == i) {
                // single day
                groups.add(DAY_ABBR_IT.get(sorted.get(start)));
            } else {
                // consecutive range
                groups.add(DAY_ABBR_IT.get(sorted.get(start)) + "-" + DAY_ABBR_IT.get(sorted.get(i)));
            }

            i++;
        }

        return String.join(", ", groups);
    }
    
    
}