# Note: the context of the comments is specified. 
#   GENERIC = considerations about an image, internal workings etc.
#   LOCAL = my local config only, it might not apply to your local config

# ********** SUMMARY OF SERVICES ********************
# ------------------------------------------------
#      SERVICE              |       ADDRESS
# ----------------------------------------------
#    localhost:3001               web server (java)
#    localhost:5433               database (postgres)


services:
  # server  
  server:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      # I have an application-local.properties (LOCAL)      
      SPRING_PROFILES_ACTIVE: local
      # when run with Docker, override the database url (GENERIC)
      #   the host "postgres" will be resolved by the internal Docker DNS,
      #   which is why the port must be the container port, not the host port      
      JDBC_DATABASE_URL: jdbc:postgresql://postgres:5432/operavion-crm
  # database      
  postgres:
    image: "postgres:18-alpine"
    environment:
      # local use only      
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: operavion-crm
    ports:
      # changed host port because at port 5432 is pure postgres (LOCAL)      
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  # if you don't specify a volumne, postgres will create one for you. (GENERIC)
  postgres-data: 