-- public.addresses definition

-- Drop table

-- DROP TABLE public.addresses;

CREATE TABLE public.addresses (
                                  id uuid NOT NULL,
                                  display_name varchar(255) NOT NULL,
                                  lat float8 NOT NULL,
                                  lon float8 NOT NULL,
                                  CONSTRAINT addresses_pkey PRIMARY KEY (id)
);


-- public.companies definition

-- Drop table

-- DROP TABLE public.companies;

CREATE TABLE public.companies (
                                  id uuid NOT NULL,
                                  created_at timestamptz(6) NOT NULL,
                                  email varchar(255) NOT NULL,
                                  legal_name varchar(255) NOT NULL,
                                  stripe_customer_id varchar(255) NULL,
                                  stripe_subscription_status varchar(255) NOT NULL,
                                  CONSTRAINT companies_pkey PRIMARY KEY (id),
                                  CONSTRAINT companies_stripe_subscription_status_check CHECK (((stripe_subscription_status)::text = ANY ((ARRAY['INCOMPLETE'::character varying, 'TRIALING'::character varying, 'ACTIVE'::character varying, 'PAST_DUE'::character varying, 'CANCELED'::character varying])::text[]))),
                                  CONSTRAINT ukl1y91vhxurg19rpq86fmhb62b UNIQUE (stripe_customer_id),
                                  CONSTRAINT ukqjgsqh1oq7xhof2tdte9l7e2b UNIQUE (email)
);


-- public.job_executions definition

-- Drop table

-- DROP TABLE public.job_executions;

CREATE TABLE public.job_executions (
                                       id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                       finished_at timestamptz(6) NULL,
                                       job_name varchar(255) NOT NULL,
                                       last_processed_item_id uuid NOT NULL,
                                       message text NOT NULL,
                                       metadata jsonb NULL,
                                       retry_count int4 NOT NULL,
                                       started_at timestamptz(6) NOT NULL,
                                       state varchar(255) NOT NULL,
                                       CONSTRAINT job_executions_pkey PRIMARY KEY (id),
                                       CONSTRAINT job_executions_state_check CHECK (((state)::text = ANY ((ARRAY['INCOMPLETE'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'ABANDONED'::character varying])::text[])))
);







-- public.checklists definition

-- Drop table

-- DROP TABLE public.checklists;

CREATE TABLE public.checklists (
                                   id uuid NOT NULL,
                                   "name" varchar(255) NOT NULL,
                                   company_id uuid NOT NULL,
                                   CONSTRAINT checklists_pkey PRIMARY KEY (id),
                                   CONSTRAINT fksxlbt4r73nws0m3dxcd35xymf FOREIGN KEY (company_id) REFERENCES public.companies(id)
);





-- public.clients definition

-- Drop table

-- DROP TABLE public.clients;

CREATE TABLE public.clients (
                                id uuid NOT NULL,
                                email varchar(255) NOT NULL,
                                legal_name varchar(255) NOT NULL,
                                phone varchar(255) NOT NULL,
                                vat varchar(255) NOT NULL,
                                company_id uuid NOT NULL,
                                legal_address_id uuid NOT NULL,
                                CONSTRAINT clients_pkey PRIMARY KEY (id),
                                CONSTRAINT fkr5764n58kkrj30ciytbr03tha FOREIGN KEY (legal_address_id) REFERENCES public.addresses(id),
                                CONSTRAINT fks3vg3lr3eadee5luiq6c78t1i FOREIGN KEY (company_id) REFERENCES public.companies(id)
);







-- public.tasks definition

-- Drop table

-- DROP TABLE public.tasks;

CREATE TABLE public.tasks (
                              id uuid NOT NULL,
                              "name" varchar(255) NOT NULL,
                              company_id uuid NOT NULL,
                              CONSTRAINT tasks_pkey PRIMARY KEY (id),
                              CONSTRAINT fkbh9q59h29103iapm3f9px5xm2 FOREIGN KEY (company_id) REFERENCES public.companies(id)
);


-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
                              id uuid NOT NULL,
                              avatar_url varchar(255) NOT NULL,
                              created_at timestamptz(6) NOT NULL,
                              email varchar(255) NULL,
                              firstname varchar(255) NOT NULL,
                              lastname varchar(255) NOT NULL,
                              "password" varchar(255) NOT NULL,
                              password_change_required bool NOT NULL,
                              password_changed bool NOT NULL,
                              "role" varchar(255) NOT NULL,
                              username varchar(255) NOT NULL,
                              verified_email bool NOT NULL,
                              verified_email_required bool NOT NULL,
                              company_id uuid NOT NULL,
                              CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
                              CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username),
                              CONSTRAINT users_pkey PRIMARY KEY (id),
                              CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'COORDINATOR'::character varying, 'OPERATOR'::character varying])::text[]))),
                              CONSTRAINT fkin8gn4o1hpiwe6qe4ey7ykwq7 FOREIGN KEY (company_id) REFERENCES public.companies(id)
);




-- public.articles definition

-- Drop table

-- DROP TABLE public.articles;

CREATE TABLE public.articles (
                                 article_id uuid NOT NULL,
                                 "content" varchar(255) NOT NULL,
                                 cover_url varchar(255) NOT NULL,
                                 created_at timestamptz(6) NOT NULL,
                                 title varchar(255) NOT NULL,
                                 user_id uuid NOT NULL,
                                 CONSTRAINT articles_pkey PRIMARY KEY (article_id),
                                 CONSTRAINT fklc3sm3utetrj1sx4v9ahwopnr FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.checklist_entries definition

-- Drop table

-- DROP TABLE public.checklist_entries;

CREATE TABLE public.checklist_entries (
                                          id uuid NOT NULL,
                                          "position" int4 NOT NULL,
                                          checklist_id uuid NOT NULL,
                                          task_id uuid NOT NULL,
                                          CONSTRAINT checklist_entries_pkey PRIMARY KEY (id),
                                          CONSTRAINT ukobr0sjukanit7uu1r22rgc3hc UNIQUE (checklist_id, "position"),
                                          CONSTRAINT fk2nxbirdfvfvx96bjrmqxv4roq FOREIGN KEY (task_id) REFERENCES public.tasks(id),
                                          CONSTRAINT fk67i7pbie5mkswavb3kbek759f FOREIGN KEY (checklist_id) REFERENCES public.checklists(id)
);


-- public.client_addresses definition

-- Drop table

-- DROP TABLE public.client_addresses;

CREATE TABLE public.client_addresses (
                                         id uuid NOT NULL,
                                         address_name varchar(255) NOT NULL,
                                         address_id uuid NOT NULL,
                                         client_id uuid NOT NULL,
                                         CONSTRAINT client_addresses_pkey PRIMARY KEY (id),
                                         CONSTRAINT uki78u1hfx00e3we0ey2hrwrbnb UNIQUE (client_id, address_id),
                                         CONSTRAINT fkfvp9pv0pmcoffy8m8guxbisp1 FOREIGN KEY (address_id) REFERENCES public.addresses(id),
                                         CONSTRAINT fkg30vec92o6rgxx6sbk9r0l43d FOREIGN KEY (client_id) REFERENCES public.clients(id)
);


-- public.contract_expectations definition

-- Drop table

-- DROP TABLE public.contract_expectations;

CREATE TABLE public.contract_expectations (
                                              id uuid NOT NULL,
                                              expectations text NOT NULL,
                                              processed_at timestamptz(6) NOT NULL,
                                              state varchar(255) NULL,
                                              client_address_id uuid NOT NULL,
                                              CONSTRAINT contract_expectations_pkey PRIMARY KEY (id),
                                              CONSTRAINT contract_expectations_state_check CHECK (((state)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying])::text[]))),
                                              CONSTRAINT uk47wkhkxuefn4u50uu9ks4dbid UNIQUE (client_address_id),
                                              CONSTRAINT fklf7tvd66ilnie2snstcnpe06k FOREIGN KEY (client_address_id) REFERENCES public.client_addresses(id)
);


-- public.email_verification_codes definition

-- Drop table

-- DROP TABLE public.email_verification_codes;

CREATE TABLE public.email_verification_codes (
                                                 code uuid NOT NULL,
                                                 created_at timestamptz(6) NOT NULL,
                                                 used bool NOT NULL,
                                                 user_id uuid NOT NULL,
                                                 CONSTRAINT email_verification_codes_pkey PRIMARY KEY (code),
                                                 CONSTRAINT fkpjww6kxejvkaaivcg6vv7r9w9 FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.forgot_password_codes definition

-- Drop table

-- DROP TABLE public.forgot_password_codes;

CREATE TABLE public.forgot_password_codes (
                                              code uuid NOT NULL,
                                              clicked bool NOT NULL,
                                              created_at timestamptz(6) NULL,
                                              usable bool NOT NULL,
                                              used bool NOT NULL,
                                              user_id uuid NOT NULL,
                                              CONSTRAINT forgot_password_codes_pkey PRIMARY KEY (code),
                                              CONSTRAINT fk9h3f1cx5s76u81tiktaa99pkn FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.notifications definition

-- Drop table

-- DROP TABLE public.notifications;

CREATE TABLE public.notifications (
                                      notification_id uuid NOT NULL,
                                      body varchar(255) NOT NULL,
                                      created_at timestamptz(6) NOT NULL,
                                      "data" jsonb NULL,
                                      expires_at timestamptz(6) NULL,
                                      read_at timestamptz(6) NULL,
                                      title varchar(255) NOT NULL,
                                      "type" varchar(255) NOT NULL,
                                      user_id uuid NOT NULL,
                                      CONSTRAINT notifications_pkey PRIMARY KEY (notification_id),
                                      CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.shifts definition

-- Drop table

-- DROP TABLE public.shifts;

CREATE TABLE public.shifts (
                               id uuid NOT NULL,
                               end_date date NOT NULL,
                               end_time time(0) NOT NULL,
                               start_date date NOT NULL,
                               start_time time(0) NOT NULL,
                               checklist_id uuid NOT NULL,
                               client_address_id uuid NOT NULL,
                               CONSTRAINT shifts_pkey PRIMARY KEY (id),
                               CONSTRAINT fken583stf2iwe9a8o9bj86t4o FOREIGN KEY (checklist_id) REFERENCES public.checklists(id),
                               CONSTRAINT fks0teayuyn8051hger3ra4kayw FOREIGN KEY (client_address_id) REFERENCES public.client_addresses(id)
);


-- public.client_address_checklists definition

-- Drop table

-- DROP TABLE public.client_address_checklists;

CREATE TABLE public.client_address_checklists (
                                                  id uuid NOT NULL,
                                                  checklist_id uuid NOT NULL,
                                                  client_address_id uuid NOT NULL,
                                                  CONSTRAINT client_address_checklists_pkey PRIMARY KEY (id),
                                                  CONSTRAINT ukhr553w505kgtmsibcq34nxy7q UNIQUE (client_address_id, checklist_id),
                                                  CONSTRAINT fkg7h17g8l26sg024vmrpohmys2 FOREIGN KEY (checklist_id) REFERENCES public.checklists(id),
                                                  CONSTRAINT fkjj5jk3pcrdf2pbpje4cmtjbg9 FOREIGN KEY (client_address_id) REFERENCES public.client_addresses(id)
);


-- public.shift_days definition

-- Drop table

-- DROP TABLE public.shift_days;

CREATE TABLE public.shift_days (
                                   id uuid NOT NULL,
                                   "day" varchar(255) NOT NULL,
                                   shift_id uuid NOT NULL,
                                   CONSTRAINT shift_days_day_check CHECK (((day)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[]))),
                                   CONSTRAINT shift_days_pkey PRIMARY KEY (id),
                                   CONSTRAINT ukf3s8bybuq7fuq85oquintfies UNIQUE (shift_id, day),
                                   CONSTRAINT fk7me29ky1k40skvu5nn65e8vhy FOREIGN KEY (shift_id) REFERENCES public.shifts(id)
);


-- public.shift_operators definition

-- Drop table

-- DROP TABLE public.shift_operators;

CREATE TABLE public.shift_operators (
                                        id uuid NOT NULL,
                                        operator_id uuid NOT NULL,
                                        shift_id uuid NOT NULL,
                                        CONSTRAINT shift_operators_pkey PRIMARY KEY (id),
                                        CONSTRAINT ukddcbu4fc2y61aqy9uau4xc35e UNIQUE (shift_id, operator_id),
                                        CONSTRAINT fkbkn2ovvxmy4trvsn5vw64g162 FOREIGN KEY (shift_id) REFERENCES public.shifts(id),
                                        CONSTRAINT fkfaw7ppw5jobcqf6mpa9vaygxm FOREIGN KEY (operator_id) REFERENCES public.users(id)
);


-- public.tasks_completion definition

-- Drop table

-- DROP TABLE public.tasks_completion;

CREATE TABLE public.tasks_completion (
                                         id uuid NOT NULL,
                                         completed bool NOT NULL,
                                         completed_at timestamptz(6) NOT NULL,
                                         checklist_entry_id uuid NOT NULL,
                                         shift_operator_id uuid NOT NULL,
                                         CONSTRAINT tasks_completion_pkey PRIMARY KEY (id),
                                         CONSTRAINT ukbjcrln6wqk02swvfv35emy4w9 UNIQUE (shift_operator_id, checklist_entry_id),
                                         CONSTRAINT fk2amammnotdg35k2jecw1704t5 FOREIGN KEY (checklist_entry_id) REFERENCES public.checklist_entries(id),
                                         CONSTRAINT fkf00x8j4gl0trolxty9ekgl9sf FOREIGN KEY (shift_operator_id) REFERENCES public.shift_operators(id)
);